### ISSUE TITLE
sensor.picnic_delivery only shows latest delivery window

### ISSUE THREAD

**Issue by GitHubxtsnl** [MikeBrink/home-assistant-picnic#12]
I really like this integration. I use it for announcing the upcoming delivery time of my groceries via my sonos speakers :-)

when I look at the sensor.picnic_delivery it shows the 'window_start: '2021-02-11T21:00:00+01:00' This is the delivery window.
I currently have 2 active deliveries scheduled, one today and one tomorrow.
The sensor.picnic_delivery only shows the latest delivery window, the one for tomorrow. Where can I find the delivery window of the next upcoming delivery, not the latest delivery?

```
attribution: Information provided by Picnic.app
delivery:
  creation_time: '2021-02-08T10:09:16.204+01:00'
  delivery_id: z7nlrwbxxxxxx
  slot_id: 6010ad088b2ad94cf38xxxxx
  hub_id: ARN
  fc_id: FC5
  window_start: '2021-02-11T21:00:00+01:00'
  window_end: '2021-02-11T22:00:00+01:00'
  cut_off_time: '2021-02-10T22:00:00+01:00'
  is_available: true
  selected: false
  reserved: false
  minimum_order_value: 3500
friendly_name: picnic_delivery
icon: 'mdi:truck-delivery'

```

currently running the latst version available from HACS.
